p3

diff --git a/p3/Makefile b/p3/Makefile
--- a/p3/Makefile
+++ b/p3/Makefile
@@ -52,23 +52,23 @@ OBJDUMP := objdump
 # Emulator Options
 ################################################################################
 
-#If the makefile can't find QEMU, specify its path here
-QEMU := /usr/bin/qemu-system-i386
+# If the makefile can't find QEMU, specify its path here
+#QEMU :=
 
 # Try to infer the correct QEMU if not specified
-# ifndef QEMU
-# QEMU := $(shell if which qemu 1> /dev/null 2> /dev/null; \
-# 	then echo qemu; exit; \
-# 	else \
-# 	qemu=/p/course/cs537-remzi/ta/tools/qemu; \
-# 	if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
-# 	echo "***" 1>&2; \
-# 	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
-# 	echo "*** Is the directory containing the qemu binary in your " 1>&2; \
-# 	echo "*** PATH or have you tried setting the QEMU variable in " 1>&2; \
-# 	echo "*** Makefile?" 1>&2; \
-# 	echo "***" 1>&2; exit 1)
-# endif
+ifndef QEMU
+QEMU := $(shell if which qemu 1> /dev/null 2> /dev/null; \
+	then echo qemu; exit; \
+	else \
+	qemu=/p/course/cs537-remzi/ta/tools/qemu; \
+	if test -x $$qemu; then echo $$qemu; exit; fi; fi; \
+	echo "***" 1>&2; \
+	echo "*** Error: Couldn't find a working QEMU executable." 1>&2; \
+	echo "*** Is the directory containing the qemu binary in your " 1>&2; \
+	echo "*** PATH or have you tried setting the QEMU variable in " 1>&2; \
+	echo "*** Makefile?" 1>&2; \
+	echo "***" 1>&2; exit 1)
+endif
 
 # try to generate a unique GDB port
 GDBPORT := $(shell expr `id -u` % 5000 + 25000)
